name: fuzz
on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'MAINTAINERS'

permissions:
  contents: read

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Smoke test Fuzzers
        run: make fuzz-smoketest
        env:
          SKIP_COSIGN_VERIFICATION: true
